spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/risk_decision_engine_develop?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      ### 连接池的配置信息 ###
      initialSize: 5
      minIdle: 5
      maxActive: 20
      ### 配置获取连接等待超时的时间 ###
      maxWait: 60000
      ### 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 ###
      timeBetweenEvictionRunsMillis: 60000
      ### 配置一个连接在池中最小生存的时间，单位是毫秒 ###
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      ### 打开PSCache，并且指定每个连接上PSCache的大小 ###
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      ### 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 ###
      filters: stat,log4j2
      ### 通过connectProperties属性来打开mergeSql功能；慢SQL记录 ###
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
      # StatViewServlet配置。（因为暴露的监控信息比较敏感，支持密码加密和访问ip限定）
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: 123456
        allow:
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.css,*.gif,*.jpg,*.png,*.ico,/druid/*"

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: false